---
---
<link rel="stylesheet" href="styles.css" type="text/css">
    
### presentations
<hr />

<br>

##### Invited	

<br>

Meershoek, A.J.A., **Veen, D.** (2018, May). Duo presentation: Treatment of internal carotid artery NEar occlusiON (NEON study): An individual patient data meta-analysis. Presentation delivered at research meeting of UMC Utrecht Department of Vascular Surgery, Utrecht, the Netherlands.

**Veen, D.** (2018, February).  On Using Expert Knowledge as Prior Information. Presentation delivered at Statistics Netherlands (CBS), Heerlen, the Netherlands. 

<br>

##### International	

<br>

**Veen, D.**, Klaassen F. (2018, July) Duo presentation: On reasons to use subjective Bayes. Presentation delivered at VIII European Congress of Methodology. Part of the symposium entitled, “Applying Subjective Bayes to Real Life Data”, Jena, Germany. 

**Veen, D.**, Stoel, D., Schalken, N. & van de Schoot, R. (2018, July). Using the Data Agreement Criterion to Rank Experts’ Beliefs. Presentation delivered at Bayesian Young Statisticians Meeting (BaYSM) 2018, Coventry, Great Britain. 

Egberts, M. & **Veen, D.** (2018, March) Duo presentation: Increasing Power of Statistical Analyses Through Collaboration. Presentation delivered at Small Sample Size Solutions (S4) Conference, Utrecht, the Netherlands.

de Klerk, M. & **Veen, D.** (2018, March) Duo presentation: Improving the Assessment of Individual Phoneme Discrimination Performance. Presentation delivered at Small Sample Size Solutions (S4) Conference, Utrecht, the Netherlands.

**Veen, D.**, van Loey, N.E.E., van Baar, A.L., Wijnen, F.N.K. & van de Schoot, R. (2017, August). Eliciting and Using Expert Information in Latent Growth Curve Models. Poster presented at 18th European Conference on Developmental Psychology, Utrecht, the Netherlands.

**Veen, D.**, Izeboud, E. & van de Schoot, R. (2017, May). Systematic Review of Elicitation Software: Expert Knowledge as a Source of Data. Part of the symposium entitled, “Experts and Animals: How Can They Help Us?” at the 29th Association for Psychological Science (APS) annual convention, Boston, MA, USA.

**Veen, D.**, Stoel, D., & van de Schoot, R. (2017, May). Using the Data Agreement Criterion to Rank Experts’ Beliefs. Part of the symposium entitled, “What the Dutch can do with prior information (and you too)” at the  Modern Modeling Methods (M3) Conference, Storrs, CT, USA.

<br>

##### National	

<br>

**Veen, D.** & van de Schoot, R. (2018, June). How understanding prior-data compromise can lead to sample size determination. Poster presented at 33rd IOPS Summer Conference, Amsterdam, the Netherlands.

**Veen, D.**, van Loey, N.E.E., van Baar, A.L., Wijnen, F.N.K. & van de Schoot, R. (2016, November). Eliciting and Using Expert Information in Latent Growth Curve Models: Research Plan. Poster presented at VNOP-CAS-ISED research days 2016, Leiden, the Netherlands.

<br>

##### Institutional	

<br>

**Veen, D.** & de Klerk, M. (2018, July). Real data application: Bayesian Hierarchical Modelling as a Tool in Assessment of Individual Discrimination Performance. Presentation delivered at Utrecht University Summer school: Advanced Multilevel Analysis, Utrecht, the Netherlands.

**Veen, D.** (2018, January). The Effects of Using Different MCMC Samplers. Presentation delivered at Utrecht University for the Bayesian Statistics working group, Utrecht, the Netherlands.

**Veen, D.** (2017, June). Expert Knowledge as a Source of Data. Presentation delivered at Utrecht University at the 1st Experts Data (Dis)Agreement working group meeting, Utrecht, the Netherlands.

Mulder, K.T., **Veen, D.** (2016, October). Bayes Meeting Default Priors. Presentation delivered at Utrecht University for the Bayesian Statistics working group, Utrecht, the Netherlands.

**Veen, D.**, Stoel, D., van de Schoot, A.G.J. (2016, September). Using the Data Agreement Criterion to Rank Experts’ Beliefs. Presentation delivered at Utrecht University for the Bayesian Statistics working group, Utrecht, the Netherlands.

<br>
