---
---
<link rel="stylesheet" href="styles.css" type="text/css">


### Academic publications
<hr />

##### Published or Accepted
<br>
**Veen, D.**, Stoel, D., Schalken, N., Mulder, K. & van de Schoot, R. (2018). Using the data agreement criterion to rank experts' beliefs. *entropy*. 20(8). doi: 10.3390/e20080592 <a href="http://www.mdpi.com/1099-4300/20/8/592/pdf" target="_blank" rel="noopener">download here</a>.

Fox, J-P, **Veen, D.**, & Klotzke, K. (2018). Generalized Linear Mixed Models for Randomized Responses. (manuscript accepted for publication in *methodology*).

**Veen, D.**, Stoel ,D., Zondervan-Zwijnenburg, M. & van de Schoot, R. (2017) Proposal for a Five-Step Method to Elicit Expert Judgment. *Front. Psychol*. 8:2110. doi: 10.3389/fpsyg.2017.02110 <a href="doc/proposal_for_a_five_step_method.pdf" target="_blank" rel="noopener">download here</a>.

<br>

##### Under review
<br>
Schalken, N., **Veen, D.**, & van de Schoot, R. (2018). Exploring the Data Agreement Criterion as a tool for the evaluation and ranking of expert priors. (manuscript under review).

Meershoek, A.J.A., de Vries, E.E., **Veen, D.**, den Ruijter, H.M., & de Borst, G.J. (2018).
Treatment of internal carotid artery NEar occlusiON (NEON study): An individual patient data meta-analysis. (manuscript under review).

**Veen, D.**, Little, T.D. & van de Schoot, R. (2018). Effects Coding as Unbiased Alternative to Scale Scores. (manuscript under review).

de Klerk, M., **Veen, D.**, Wijnen, F. & de Bree, E. (2018). A Step Forward: Bayesian Hierarchical Modelling as a Tool in Assessment of Individual Discrimination Performance. (manuscript under review).

<br>

### Technical Report
<hr />

Luyten, H., **Veen, D.** & Meelissen, M.R.M. (2015). De relatie tussen leerling- en
schoolkenmerken en digitale geletterdheid van 14-jarigen: secundaire analyses op de data van ICILS-2013. Enschede: Universiteit Twente  <a href="doc/ICILS_2013_report.pdf" target="_blank" rel="noopener">download here</a>.

