---
title: "Resume"
---
<link rel="stylesheet" href="styles.css" type="text/css">

Download my full Resume <a href="doc/online_resume_july_2018.pdf" target="_blank" rel="noopener">here</a>.


<h2>Employment</h2>

<hr />

<b>Utrecht University, Faculty of Social Sciences, Department of Methodology & Statistics</b>
<span style="color:#999999;"><b>PhD Candidate - 08/2016 - present</b></span>
Developing new methodology to use expert knowledge as input in latent growth curve models to counterbalance issues of small sample sizes.

<b>ProfitWise International</b>
<span style="color:#999999;"><b>Methodological Development Intern - 09/2015 - 05/2016</b></span>
Collaborating on the development of new statistical, business analytical, methods. After the development of the new methods we conducted studies at a staffing company and a large financial institution to test the methods that resulted from the collaboration.

<b>University of Twente / Utrecht University</b>
<span style="color:#999999;"><b>Student Assistant Research Master Course: Survey Data Analysis - 09/2015 - 12/2015</b></span>
Assisting in the structuring of practicals and teaching in the form of supporting sessions for the students in which they can ask questions about lectures and practicals.

<b>University of Twente, Faculty of Behavioural, Management and Social Science, Department of Research Methodology, Measurement and Data Analysis</b>
<span style="color:#999999;"><b>Data Analyst - 06/2015 - 07/2015</b></span>
Multilevel analysis on ICILS 2013 data using HLM software for Kennisnet foundation (Dutch expertise centre on ICT in education). The research report can be found<a><href="http://nebula.wsimg.com/5df8b24242280a6a927da6905907e139?AccessKeyId=7991897C9084F0F69E3C&disposition=0&alloworigin=1" target="_blank" rel="noopener">here</a>.
<h2>Education</h2>

<hr />

<b>Methodology and Statistics for the Behavioural, Biomedical and Social Sciences - Research Master (MSc) </b>
<span style="color:#999999;"><b>Utrecht University - Cum Laude (GPA = 4.0) - 2014 - 2016 </b></span>
Courses: Survey data analysis, Multivariate statistics, Fundamentals of statistics, Computational inference with R, Psychometrics, Introduction to multilevel and structural equation modelling, Bayesian statistics, Clinical research designs, elective: survey track.

<b>Psychology - Bachelor (BSc) </b>
<span style="color:#999999;"><b>University of Twente - 2010 - 2014 </b></span>
Minor: Origins (Cosmology, Biological evolution and Philosophy of Awareness)
<a href="http://nebula.wsimg.com/6e21abcdee85a72ab65bad66f72795c6?AccessKeyId=7991897C9084F0F69E3C&disposition=0&alloworigin=1" target="_blank" rel="noopener">Bachelor Thesis</a>: “Multivariate analysis for using the Crosswise- and Triangular method” (These are Randomized Response data collection methods)

<hr />


